version: '2.1'
orbs:
  ms-teams-notifier: oktapodia/ms-teams-notifier@1.0.0
jobs:
  build:
    executor: docker
    steps:
      - ms-teams-notifier/report:
          only_on_fail: false
          webhook_url: $MS_TEAMS_WEBHOOK_URL
